export const PLAYERS_DUM = [
    {
        name: "Precious",
        address: "p1",
        lands: [],
        character: "pink",
        cash: 0,
        position: "land-1",
        turn: 0,
        pendingRent: false,
    },
    {
        name: "Precious2",
        address: "p2",
        lands: [],
        character: "yellow",
        cash: 0,
        position: "land-1",
        turn: 1,
        pendingRent: false,
    },
    {
        name: "Precious3",
        address: "p3",
        lands: [],
        character: "orange",
        cash: 0,
        position: "land-1",
        turn: 2,
        pendingRent: false,
    },
    {
        name: "Precious4",
        address: "p4",
        lands: [],
        character: "blue",
        cash: 0,
        position: "land-1",
        turn: 3,
        pendingRent: false,
    }
]