export const LANDS = [
    {
        id: "c1",
        type: "aux", // deed, aux,
        setID: "",
        color: "black",
        name: "GO",
        rent: 0,
        mortgageFactor: 0,
        unmortgageFactor: 0,
        price: 0,
        maxHouses: 0,
        maxHotels: 0,
        houseRentFactor: 0,
        image: "hello",
        startPos: [1, 1],
        endPos: [3, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-1",
        color: "purple",
        name: "Old Kent Road",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 4],
        endPos: [3, 5],
    },
    {
        id: "c1",
        type: "lightgreen", // deed, aux,
        setID: "",
        color: "grey",
        name: "Community Chest",
        rent: 0,
        mortgageFactor: 0,
        unmortgageFactor: 0,
        price: 0,
        maxHouses: 0,
        maxHotels: 0,
        houseRentFactor: 0,
        image: "hello",
        startPos: [1, 6],
        endPos: [3, 7],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-1",
        color: "purple",
        name: "Whitechapel Road",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 60,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 8],
        endPos: [3, 9],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "black",
        name: "Income Task",
        rent: 2000,
        mortgageFactor: 0,
        unmortgageFactor: 0,
        price: 0,
        maxHouses: 0,
        maxHotels: 0,
        houseRentFactor: 0,
        image: "hello",
        startPos: [1, 10],
        endPos: [3, 11],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-22",
        color: "white",
        name: "Kings Cross Station",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 100,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 12],
        endPos: [3, 13],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-2",
        color: "lightblue",
        name: "The Angel Islington",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 100,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 14],
        endPos: [3, 15],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-2",
        color: "lightblue",
        name: "Euston Road",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 120,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 16],
        endPos: [3, 17],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "black",
        name: "Chance",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 18],
        endPos: [3, 19],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-2",
        color: "lightblue",
        name: "Pentonville Road",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 20],
        endPos: [3, 21],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "orange",
        name: "Jail",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 22],
        endPos: [3, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-3",
        color: "#4a0000",
        name: "Pall Mall",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 140,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [4, 22],
        endPos: [5, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-23",
        color: "white",
        name: "Electric Company",
        rent: 1,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 150,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [6, 22],
        endPos: [7, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-3",
        color: "#4a0000",
        name: "Whitehall",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 140,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [8, 22],
        endPos: [9, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-3",
        color: "#4a0000",
        name: "Northumberland Avenue",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 160,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [10, 22],
        endPos: [11, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-22",
        color: "white",
        name: "Marylebone Station",
        rent: 25,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [12, 22],
        endPos: [13, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-4",
        color: "orange",
        name: "Bow Street",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 180,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [14, 22],
        endPos: [15, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "grey",
        name: "Community Chest",
        rent: 0,
        mortgageFactor: 0,
        unmortgageFactor: 0,
        price: 0,
        maxHouses: 0,
        maxHotels: 0,
        houseRentFactor: 0,
        image: "hello",
        startPos: [16, 22],
        endPos: [17, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-4",
        color: "orange",
        name: "Marlborough Street",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 180,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [18, 22],
        endPos: [19, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-4",
        color: "orange",
        name: "Vine Street",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [20, 22],
        endPos: [21, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "red",
        name: "Free Parking",
        rent: 0,
        mortgageFactor: 0,
        unmortgageFactor: 0,
        price: 0,
        maxHouses: 0,
        maxHotels: 0,
        houseRentFactor: 0,
        image: "hello",
        startPos: [22, 22],
        endPos: [24, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-5",
        color: "red",
        name: "The Strand",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 220,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 20],
        endPos: [24, 21],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "grey",
        name: "Chance",
        rent: 0,
        mortgageFactor: 0,
        unmortgageFactor: 0,
        price: 0,
        maxHouses: 0,
        maxHotels: 0,
        houseRentFactor: 0,
        image: "hello",
        startPos: [22, 18],
        endPos: [24, 19],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-5",
        color: "red",
        name: "Fleet Street",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 220,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 16],
        endPos: [24, 17],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-5",
        color: "red",
        name: "Trafalger Square",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 240,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 14],
        endPos: [24, 15],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-22",
        color: "white",
        name: "Fenchurch Square",
        rent: 25,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 12],
        endPos: [24, 13],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-6",
        color: "yellow",
        name: "Leicester Sqaure",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 260,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 10],
        endPos: [24, 11],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-6",
        color: "yellow",
        name: "Coventry Street",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 8],
        endPos: [24, 9],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-23",
        color: "lightgreen",
        name: "Water Works",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 150,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 6],
        endPos: [24, 7],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-6",
        color: "yellow",
        name: "Piccadilly",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 4],
        endPos: [24, 5],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "blue",
        name: "Go To Jail",
        rent: 0,
        mortgageFactor: 0,
        unmortgageFactor: 0,
        price: 0,
        maxHouses: 0,
        maxHotels: 0,
        houseRentFactor: 0,
        image: "hello",
        startPos: [22, 1],
        endPos: [24, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-7",
        color: "green",
        name: "Regent Street",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 300,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [20, 1],
        endPos: [21, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-7",
        color: "green",
        name: "Oxford Street",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 300,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [18, 1],
        endPos: [19, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "grey",
        name: "Community Chest",
        rent: 0,
        mortgageFactor: 0,
        unmortgageFactor: 0,
        price: 0,
        maxHouses: 0,
        maxHotels: 0,
        houseRentFactor: 0,
        image: "hello",
        startPos: [16, 1],
        endPos: [17, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-7",
        color: "green",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [14, 1],
        endPos: [15, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-22",
        color: "white",
        name: "Liverpool Street Station",
        rent: 25,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2,
        image: "hello",
        startPos: [12, 1],
        endPos: [13, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "black",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 0,
        maxHotels: 0,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [10, 1],
        endPos: [11, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-8",
        color: "blue",
        name: "Park lane",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 350,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [8, 1],
        endPos: [9, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "grey",
        name: "Pay 750",
        rent: 750,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 0,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [6, 1],
        endPos: [7, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "set-8",
        color: "blue",
        name: "Mayfair",
        rent: 100,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 400,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [4, 1],
        endPos: [5, 3],
    },
]

export const LAND_SETS = [
    {
        id: "set-1",
        name: "",
        color: "purple",
        rentWithSetFactor: 0,
        sellable: false,
    },
    {
        id: "set-2",
        name: "Precious Avenue",
        color: "lightblue",
        rentWithSetFactor: 2,
        sellable: false,
    },
    {
        id: "set-3",
        name: "Precious Avenue",
        color: "#4a0000",
        rentWithSetFactor: 2,
        sellable: false,
    },
    {
        id: "set-4",
        name: "Precious Avenue",
        color: "orange",
        rentWithSetFactor: 2,
        sellable: false,
    },
    {
        id: "set-5",
        name: "Precious Avenue",
        color: "red",
        rentWithSetFactor: 2,
        sellable: false,
    },
    {
        id: "set-6",
        name: "Precious Avenue",
        color: "yellow",
        rentWithSetFactor: 2,
        sellable: false,
    },
    {
        id: "set-7",
        name: "Precious Avenue",
        color: "green",
        rentWithSetFactor: 2,
        sellable: false,
    },
    {
        id: "set-8",
        name: "Precious Avenue",
        color: "blue",
        rentWithSetFactor: 2,
        sellable: false,
    },

]

export const CHARACTERS = [
    "red", "blue", "green", "yellow", "pink", "brown", 
]