export const LANDS = [
    {
        id: "c1",
        type: "aux", // deed, aux,
        setID: "",
        color: "black",
        name: "GO",
        rent: 0,
        mortgageFactor: 0,
        unmortgageFactor: 0,
        price: 0,
        maxHouses: 0,
        maxHotels: 0,
        houseRentFactor: 0,
        image: "hello",
        startPos: [1, 1],
        endPos: [3, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "purple",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 4],
        endPos: [3, 5],
    },
    {
        id: "c1",
        type: "lightgreen", // deed, aux,
        setID: "",
        color: "grey",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 6],
        endPos: [3, 7],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "purple",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 8],
        endPos: [3, 9],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "black",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 10],
        endPos: [3, 11],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "white",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 12],
        endPos: [3, 13],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "lightblue",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 14],
        endPos: [3, 15],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "lightblue",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 16],
        endPos: [3, 17],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "black",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 18],
        endPos: [3, 19],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "lightblue",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 20],
        endPos: [3, 21],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "orange",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [1, 22],
        endPos: [3, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "red",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [4, 22],
        endPos: [5, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "white",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [6, 22],
        endPos: [7, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "red",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [8, 22],
        endPos: [9, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "red",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [10, 22],
        endPos: [11, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "white",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [12, 22],
        endPos: [13, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "orange",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [14, 22],
        endPos: [15, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "grey",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [16, 22],
        endPos: [17, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "orange",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [18, 22],
        endPos: [19, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "orange",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [20, 22],
        endPos: [21, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "red",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 22],
        endPos: [24, 24],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "red",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 20],
        endPos: [24, 21],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "grey",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 18],
        endPos: [24, 19],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "red",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 16],
        endPos: [24, 17],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "red",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 14],
        endPos: [24, 15],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "white",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 12],
        endPos: [24, 13],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "yellow",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 10],
        endPos: [24, 11],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "yellow",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 8],
        endPos: [24, 9],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "white",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 6],
        endPos: [24, 7],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "yellow",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 4],
        endPos: [24, 5],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "blue",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [22, 1],
        endPos: [24, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "green",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [20, 1],
        endPos: [21, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "green",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [18, 1],
        endPos: [19, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "grey",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [16, 1],
        endPos: [17, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "green",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [14, 1],
        endPos: [15, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "white",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [12, 1],
        endPos: [13, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "black",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [10, 1],
        endPos: [11, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "blue",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [8, 1],
        endPos: [9, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "grey",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [6, 1],
        endPos: [7, 3],
    },
    {
        id: "c1",
        type: "deed", // deed, aux,
        setID: "",
        color: "blue",
        name: "Happy",
        rent: 15,
        mortgageFactor: 0.5,
        unmortgageFactor: 0.5,
        price: 200,
        maxHouses: 4,
        maxHotels: 1,
        houseRentFactor: 2.5,
        image: "hello",
        startPos: [4, 1],
        endPos: [5, 3],
    },
]

export const LAND_SETS = [
    {
        id: "set-1",
        name: "",
        color: "red",
        rentWithSetFactor: 0,
        sellable: false,
    },
    {
        id: "set-2",
        name: "Precious Avenue",
        color: "red",
        rentWithSetFactor: 2,
        sellable: false,
    },
]