import Plate from '@/components/Plate'
import Head from 'next/head'
import Grid from "@mui/material/Grid"
import Box from "@mui/material/Box"
import Players from '@/components/Players'
import Bank from '@/components/Bank'
import Logs from '@/components/Logs'
import Button from '@mui/material/Button'
import { useSelector } from 'react-redux'
import { RootState } from '@/store'
import { useRouter } from 'next/router'
import Controls from '@/components/Controls'

export default function Game() {
  const router = useRouter()
  const game = useSelector((state: RootState) => state.game)

  const {playing} = game


  return (
    <>
      <Head>
        <title>Monopoly | Chaincity</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        {!playing ? <Button onClick={() => router.push("/")}>BACK TO HOME</Button> : <Grid container spacing={2} sx={{
          width: "100vw",
          height: "100vh",
        }}>
          <Grid item xs={12} md={8} sx={{
          height: {xs: "100vw", sm: "100%"},
        }}>
          <Plate divisions={24} />
          </Grid>

          <Grid item xs={12} md={4} sx={{
          height: "100%",
        }}>
              <Grid container spacing={2} sx={{
                width: "100%",
                height: "100%",
                pt: {md: 2},
                pl: {xs: 2, md: 0},
                // justifyContent: "flex-start",
                // alignItems: "flex-start"
              }}>
                <Grid item xs={12} sm={6} md={0} sx={{
                  display: {xs: "flex", sm: "flex", md: "none"},
                  border: "1px solid red",
                  
                  }}>
                  <Controls />
                </Grid>
                <Grid item xs={12} sm={6} md={0} sx={{
                  display: {xs: "none", sm: "flex", md: "none"},
                  border: "1px solid red"

                }}>
                  <Bank />
                </Grid>
                
                <Grid item xs={12} sm={6} md={12} sx={{
                  // height: "auto"
                }}>
                <Players />
                </Grid>
                <Grid item xs={12} sm={0} md={12} sx={{
                  display: {xs: "flex", sm: "none", md: "flex"}
                }}>
                <Bank />
                </Grid>
                <Grid item xs={0} sm={0} md={12} sx={{
                  display: {xs: "none", sm: "none", md: "flex"},
                  }}>
                  <Controls />
                </Grid>
                <Grid item xs={12} sm={6} md={12} sx={{
                  display: {xs: "flex", sm: "flex", md: "none"}
                }}>
                <Logs />
                </Grid>
                
              </Grid>
          </Grid>
          <Grid item xs={0} sm={0} md={6} sx={{
                  display: {xs: "none", sm: "none", md: "flex"},
                }}>
                  <Box sx={{
                    width: "100%",
                    height: "100%",
                    pl: 2,
                    pb: 2,
                  }}>
                  <Controls />
                  </Box>
                
                </Grid>
                <Grid item xs={0} sm={0} md={6} sx={{
                  display: {xs: "none", sm: "none", md: "flex"},
                }}>
                <Box sx={{
                    width: "100%",
                    height: "100%",
                    pr: 2,
                    pb: 2,
                  }}>
                  <Logs />
                  </Box>
                </Grid>
                {/* <Grid item xs={0} sm={0} md={12} sx={{
                  display: {xs: "none", sm: "none", md: "flex"},
                }}>
                <Box sx={{}}></Box>
                </Grid> */}


        </Grid>
        
        }
       
      </main>
    </>
  )
}
